#!/usr/bin/env bash

# Regenerates the native function list used by the syntax highlighter from the
# SDK sources, so it cannot drift the way the old hand-maintained map did.
#
# Usage: scripts/gen-natives.sh [path-to-sdk]

set -euo pipefail

SDK="${1:-../primal-sdk}"
LIBRARY="${SDK}/lib/compiler/library"
OUTPUT="public/js/primal-natives.js"

# Every native declares itself as `name: 'some_function',` in its own Dart file.
# A shape change upstream would quietly produce a shorter list, so the count is
# checked below rather than trusted.
MINIMUM_EXPECTED=250

if [ ! -d "${LIBRARY}" ]; then
  echo "error: ${LIBRARY} not found (pass the SDK path as the first argument)" >&2
  exit 1
fi

NAMES=$(grep -rhoE "name: '[a-zA-Z0-9_]+'," "${LIBRARY}" | grep -oE "'[a-zA-Z0-9_]+'" | tr -d "'" | sort -u)
COUNT=$(printf '%s\n' "${NAMES}" | grep -c .)

if [ "${COUNT}" -lt "${MINIMUM_EXPECTED}" ]; then
  echo "error: found only ${COUNT} native functions, expected at least ${MINIMUM_EXPECTED}." >&2
  echo "The SDK probably stopped declaring natives as \"name: '...'\" — fix this script." >&2
  exit 1
fi

{
  echo "// Generated by scripts/gen-natives.sh from the Primal SDK. Do not edit by hand."
  echo "// ${COUNT} native functions."
  echo "const PRIMAL_NATIVES = new Set(["
  printf '%s\n' "${NAMES}" | sed "s/.*/  '&',/"
  echo "]);"
} > "${OUTPUT}"

echo "Wrote ${COUNT} native functions to ${OUTPUT}"
